name: sindebad
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # INTERNATIONALIZATION
  flutter_localizations:
    sdk: flutter

  # WIDGETS
  cupertino_icons: ^1.0.5
  # flutter_native_splash: ^2.2.16
  # flutter pub run flutter_native_splash:create
  cached_network_image: ^3.2.3
  badges: ^3.0.2
  iconsax: ^0.0.8
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  pin_code_fields: ^7.4.0
  syncfusion_flutter_datepicker: ^20.4.51
  fluttertoast: ^8.2.1
  another_flushbar: ^1.12.29
  figma_squircle: ^0.5.3
  dots_indicator: ^3.0.0
  flutter_rating_bar: ^4.0.1
  tab_indicator_styler: ^2.0.0

  # UTILS
  intl: ^0.18.0
  connectivity: ^3.0.6
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  permission_handler: ^10.2.0
  get_it: ^7.2.0
  flutter_screenutil: ^5.6.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.6
  image_picker: ^0.8.6+2

  #STATE_MANAGEMENT
  riverpod: ^2.2.0
  flutter_riverpod: ^2.2.0

  # APIS/CLIENTS
  dio: ^4.0.6
  oauth_dio: ^0.2.7
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0

  # STORAGE
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

  # FIREBASE
#  firebase_core: ^2.6.1
#  cloud_firestore: ^4.4.2
#  firebase_crashlytics: ^3.1.0

  # GIT
#  flutter_validation:
#    git:
#      url: http://github.com/hsul4n/flutter_validation.git
#      ref: 10999a190ec9261fe352dc1f0e3ef13fe74b1b60

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  # flutter pub run flutter_launcher_icons

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/png/
    - assets/icons/svg/


  fonts:
    - family: DINNextLTArabic
      fonts:
        - asset: assets/fonts/DINNextLTArabic.ttf
        - asset: assets/fonts/DINNextLTArabic-Bold-2.ttf
        - asset: assets/fonts/DINNextLTArabic-UltraLight-1.ttf
        - asset: assets/fonts/DINNextLTArabic-Regular-2.ttf
        - asset: assets/fonts/DINNextLTArabic-Medium-3.ttf
        - asset: assets/fonts/DINNextLTArabic-Medium-2.ttf
        - asset: assets/fonts/DINNextLTArabic-LIGHT-1.ttf
        - asset: assets/fonts/DINNextLTArabic-Heavy-1.ttf
        - asset: assets/fonts/DINNextLTArabic-Bold-3.ttf